[versions]
assertj = "3.27.7"
junit = "6.0.3"
kotlin = "2.1.20"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
groovy = "5.0.4"
gson = "2.13.0"
spock = "2.4-M5-groovy-4.0"
retrofit = "2.11.0"
retrofit-json = "1.9.0"
retrofit-converter = "1.0.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
kotlin-script-runtime = "org.jetbrains.kotlin:kotlin-script-runtime:2.1.20"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-converter = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy" }
groovy-swing = { module = "org.apache.groovy:groovy-swing", version.ref = "groovy" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
spock = { module = "org.spockframework:spock-core", version.ref = "spock" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "retrofit-json" }
retrofit-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-converter" }

[bundles]
junit = [
    "junit-jupiter",
    "junit-vintage",
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.0"
versions = "com.github.ben-manes.versions:0.53.0"
